apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-k8wo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-k8wo
    app.kubernetes.io/part-of: tkrw-pr712-0075-0047-app
  name: devfile-sample-k8wo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-k8wo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-k8wo
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-k8wo@sha256:c13fe7c765a87a4e15f20b1b670a231e27db3def51bf4c91251c4931dc5b4127
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
